spring.application.name=gestion-presences

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/gestion_presences
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=MySQL123!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

entreprise.heure.debut=09:00
entreprise.heure.fin=18:00
entreprise.tolerance.retard.minutes=15
entreprise.ip.autorisee= 192.168.1.22

server.port=8082